### ISSUE TITLE
Build Docker container

### ISSUE THREAD

**Issue by thewilkybarkid** [hypermedia-app/generic.hypermedia.app#41]
It'd be really useful to build a containersed version of the app.

**Comment by tpluscode** [comment]
All you need is a `Dockerfile` to build an image with this?

**Comment by thewilkybarkid** [comment]
And to push it to Docker Hub on a new release/commit.

We can start locally if you like; we'll include it in multiple projects, so would pull an image into each rather than building it there directly.

**Comment by tpluscode** [comment]
Please try tpluscode/hypermedia-app:alpha

**Comment by thewilkybarkid** [comment]
Works great, thanks!
