### ISSUE TITLE
Docker and parameters

### ISSUE THREAD

**Issue by thewilkybarkid** [hypermedia-app/generic.hypermedia.app#44]
Following on from https://github.com/hypermedia-app/generic.hypermedia.app/issues/41, I've just realised that the image does contain the parameter options (saw the 0.11.0 version number which predates them), but they can't be used when pulling in the image.

They're processed at build time, so the pulled image can't have them changed. We'd need to find a way to have them included in the already-generated `index.html` at runtime, and read from there.

**Comment by tpluscode** [comment]
Ah, you're right. The webpack plugin will inject the variable values as constants. Maybe there is a different plugins which does that

**Comment by thewilkybarkid** [comment]
@Cooryd has just pointed me to https://github.com/libero/reviewer-client/blob/297bafd658c86fa459370359f8432ea69babefa0/docs/configuration.md where they're using a global `CONFIG` object, which is a Webpack-generated file rewritten by a script at startup with the runtime variables.
