### ISSUE TITLE
Docker image doesn't accept SIGTERM

### ISSUE THREAD

**Issue by giorgiosironi** [hypermedia-app/generic.hypermedia.app#46]
Originally found out in a docker-compose setup, but believe I can reproduce with a minimal Docker command:
```
docker run --name hypermedia-app --rm tpluscode/hypermedia-app:version-0.12.1
 
Listening on http://80f7ae8985ad:8000, http://127.0.0.1:8000, http://172.17.0.2:8000
^C^C^C^C^C
```
(Ctrl+C has no effect)

Separately:
```
time docker stop hypermedia-app                                              
hypermedia-app

real    0m10.571s
user    0m0.044s
sys     0m0.024s
```
The app is killed after the 10 second grace period.

The reason is understandable as the process running is `sh` from Alpine which usually is Busybox and ignores signals as it substitutes itself with the launched process (as if it was always using `exec`). Here's a [super-hack to avoid this](https://github.com/libero/storybook/blob/58250798f0f8fb7d42a4b80a128bc08c338c99d0/Makefile#L70-L73) which I wouldn't recommend for the long term.

In some applications instead we use an `npm run` wrapper that lets `npm` act as the receiver of signals; would that be suitable here?

**Comment by tpluscode** [comment]
Oh, so that's why. I was wondering why I have to `docker kill` my containers 🤦‍♂ 

#47 seems to have done the trick. Please have a look @giorgiosironi
