### ISSUE TITLE
Empty page after an operation

### ISSUE THREAD

**Issue by thewilkybarkid** [hypermedia-app/generic.hypermedia.app#48]
Currently https://github.com/libero/article-store returns an empty `201 Created` response with a `Location` header back to the collection after its add article operation (https://github.com/libero/article-store/blob/5fd648ebfab904a0185dd4a403f38ca6765d016d/src/routes/api-documentation.ts#L56-L68). GHA performs the operation successfully, but the page is blank and links (eg `Home`) are unresponsive. I have to manually go to another resource.

It'd be helpful to follow the `Location` in this case.

/cc @nlisgo

**Comment by tpluscode** [comment]
Hey @thewilkybarkid. The UI is already doing that: https://github.com/hypermedia-app/generic.hypermedia.app/blob/master/src/components/hypermedia-app-shell/index.ts#L38-L40

Do you have a live API I could experiment with?

**Comment by thewilkybarkid** [comment]
Not yet, but it will be soon.

However, seeing this popup immediately made me think CORS, and that is the problem. 🤦‍♂

**Comment by tpluscode** [comment]
Ah yes. Cannot count any more how many times I was bitten by CORS headers
