### ISSUE TITLE
Do not render clickable links for resources which are not hydra:Link

### ISSUE THREAD

**Issue by tpluscode** [hypermedia-app/generic.hypermedia.app#6]
I'm not sure about this one.

Currently the UI will create links to resources which are not dereferencable links.

![feb-17-2019 18-28-57](https://user-images.githubusercontent.com/588128/52916635-5ca7a880-32e2-11e9-8263-e6f4b973da25.gif)

Seen above fails not only because the resource does not have an RDF representation, it actually is blocked because it's not served securely.

Either way, the property itself is not a `hydra:Link`. Should it be ignored in the UI?

Pinging @alien-mcl

**Comment by alien-mcl** [comment]
I think it is related to to [issue 15](/HydraCG/Specifications/issues/15) and the spec change from [pull 174](/HydraCG/Specifications/pull/174). We agreed on focusing on resources within API's domains.

As for external links - there is no real limit. I'd try with restricting to those that are marked as `hydra:Link` somehow. Another step would be to put some logic on the client that would try to match the links' URL to some known file extensions - it won't help you in this case anyway.

**Comment by tpluscode** [comment]
> I'd try with restricting to those that are marked as `hydra:Link` somehow

Yes, that won't be a big problem. I do that already to build a menu from the entrypoint where only `hydra:Link` properties are considered. Might as well extend the client to make this simple as currently it's on the consumer's side in my case.

**Comment by tpluscode** [comment]
~Wanted to get a second opinion on Hydra's stance. Maye we could extend that paragraph change in 
HydraCG/Specifications#174 to say that the client can default to only ever following explicit links. It may be more useful default than restricting on domain, as an API could span multiple subdomains...~

Forget it, I see that the preceding paragraph says jus that
